"""empty message

Revision ID: 21460d031e38
Revises: 43a9ecb6e317
Create Date: 2024-08-25 19:28:21.160903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21460d031e38'
down_revision = '43a9ecb6e317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    # ### end Alembic commands ###
