"""empty message

Revision ID: 2290a60e6163
Revises: 7cb6a90be567
Create Date: 2024-08-28 15:49:05.834754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2290a60e6163'
down_revision = '7cb6a90be567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('opponent_id',
               existing_type=mysql.VARCHAR(length=240),
               nullable=True)
        batch_op.alter_column('game_status',
               existing_type=mysql.ENUM('WIN', 'LOSE', 'DRAW'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_status',
               existing_type=mysql.ENUM('WIN', 'LOSE', 'DRAW'),
               nullable=False)
        batch_op.alter_column('opponent_id',
               existing_type=mysql.VARCHAR(length=240),
               nullable=False)

    # ### end Alembic commands ###
