"""empty message

Revision ID: 7bad927e325e
Revises: 21460d031e38
Create Date: 2024-08-25 21:11:44.268012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bad927e325e'
down_revision = '21460d031e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent_id', sa.String(length=240), nullable=False))
        batch_op.drop_constraint('game_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['opponent_id'], ['id'])
        batch_op.drop_column('oppenent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oppenent_id', mysql.VARCHAR(length=240), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('game_ibfk_2', 'user', ['oppenent_id'], ['id'])
        batch_op.drop_column('opponent_id')

    # ### end Alembic commands ###
