"""empty message

Revision ID: 7cb6a90be567
Revises: 7bad927e325e
Create Date: 2024-08-28 15:39:06.010446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cb6a90be567'
down_revision = '7bad927e325e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_status', sa.Enum('WAITING', 'PLAAYING', name='roomstate'), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=240),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=240),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('room_status')

    # ### end Alembic commands ###
