"""empty message

Revision ID: f41e364c968b
Revises: 
Create Date: 2024-08-28 18:12:28.514421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f41e364c968b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_status', sa.Enum('WAITING', 'PLAAYING', name='roomstate'), nullable=False))
        batch_op.alter_column('opponent_id',
               existing_type=mysql.VARCHAR(length=240),
               nullable=True)
        batch_op.alter_column('game_status',
               existing_type=mysql.ENUM('WIN', 'LOSE', 'DRAW'),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=240),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=240),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('game_status',
               existing_type=mysql.ENUM('WIN', 'LOSE', 'DRAW'),
               nullable=False)
        batch_op.alter_column('opponent_id',
               existing_type=mysql.VARCHAR(length=240),
               nullable=False)
        batch_op.drop_column('room_status')

    op.create_table('games',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opponent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_status', mysql.ENUM('WIN', 'DRAW', 'ONGOING'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
